export const WORMHOLE_SEND = 'WORMHOLE_SEND';
export const WORMHOLE_RECEIVE = 'WORMHOLE_RECEIVE';
export const WORMHOLE_GET_CODE = 'WORMHOLE_GET_CODE';
export const WORMHOLE_UPDATE_CODE = 'WORMHOLE_UPDATE_CODE';